server:
  port: 8181

logging:
  level:
    com.food.ordering.system: DEBUG

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    platform: postgres
  sql:
    init:
      ##schema-locations: classpath:init-schema.sql
      #data-locations: classpath:init-data.sql # Opcional si tambi√©n necesitas insertar datos
      mode: always # Siempre ejecuta los scripts al iniciar